config/routes.rb
Rails.application.routes.draw do
  root 'shopping_lists#index'

  resources :ingredients do
    collection do
      post 'import'
    end
  end

  get '/shopping_list', to: 'shopping_lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, :shopping_list_id, presence: true
  validates :quantity, presence: true, unless: "metric.blank?"
  validates :quantity, numericality: true, allow_nil: true

  scope :sorted, -> { order(:updated_at) }

  belongs_to :shopping_list

  # This is the expected CSS selector for an ingredient element.
  # The app with assume that any element with this class is an ingredient.
  INGREDIENT_CSS_CLASS = ".ingredients-list__item"

  def self.extract_ingredients_from_url(url)
    response = get_request_response(url)

    if response
      ingredient_elements = extract_ingredients_from_html(response.body)
      shopping_list = ShoppingList.get_or_create_first

      ingredient_elements.each do |element|
        # Get relevant information from the ingredient string.
        quantity, metric, name = self.preprocess_ingredient_text(element.text)
        Ingredient.create(name: name, quantity: quantity, metric: metric, shopping_list: shopping_list)
      end
      return true
    end
    false
  end

  def self.extract_ingredients_from_html(html)
    document = Nokogiri::HTML(html)
    # Get the elements using the ingredient CSS class.
    document.css(INGREDIENT_CSS_CLASS)
  end

  def self.preprocess_ingredient_text(text)
    # Matches a text that contains the string tbsp or tsp.
    # E.g. "Half tbsp of sugar", "3 tsp vanilla extract".
    tbsp_regex = /(.*)\s+(tbsp|tsp)\s+([\w\s\-]*)/i
    # Matches a text that contains the string g, kg, l or ml.
    # E.g. "1 l milk".
    weight_regex = /(\d+)(g|kg|l|ml)\s+([\w\s\-]*)/i
    # Matches string beginning with a number.
    # E.g. "4 oranges".
    number_regex = /(\d+)\s+([\w\s\-]*)/i

    if match = text.match(tbsp_regex)
      quantity, metric, name = match.captures
    elsif match = text.match(weight_regex)
      quantity, metric, name = match.captures
    elsif match = text.match(number_regex)
      quantity, name = match.captures
    else
      name = text
    end

    return quantity, metric, name
  end

private
    def self.get_request_response(url_string)
      url = URI.parse(url_string)

      if url.host and url.port
        req = Net::HTTP::Get.new(url.to_s)
        response = Net::HTTP.start(url.host, url.port, use_ssl: url.scheme == 'https') do |http|
          # Get the recipe from the given URL.
          http.request(req)
        end

        if response.kind_of? Net::HTTPSuccess
          return response
        end
      end

      return nil
    end
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  before_save :add_title_if_not_provided
  has_many :ingredients

  TITLE_CONST = "Shopping List"

  def add_title_if_not_provided
    if self.title.nil?
      self.title = TITLE_CONST
    end
  end

  def self.get_or_create_first
    shopping_list = ShoppingList.first

    if shopping_list.nil?
      shopping_list = ShoppingList.create(title: TITLE_CONST)
    end

    shopping_list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:edit, :update, :destroy]

  def import
    @url = params[:url]
    unless @url.blank?
      # If the ingredients could be extracted, then populate them in the list of
      # ingredients. Otherwise display an error message.
      if Ingredient.extract_ingredients_from_url(@url)
        @ingredients = ShoppingList.get_or_create_first.ingredients.sorted
        @message = "The ingredients were added to your shopping list."
        respond_to do |format|
          format.js
        end
      else
        @message = "The URL provided could not be accessed."
        respond_to do |format|
          format.js { render :import_message }
        end
      end
    else
      @message = "Please enter a URL."
      respond_to do |format|
        format.js { render :import_message }
      end
    end
  end

  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.js
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def create
    # Ensure the ingredient has a shopping_list_id set.
    shopping_list = ShoppingList.get_or_create_first
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.shopping_list_id = shopping_list.id
    @ingredients = shopping_list.ingredients.sorted

    respond_to do |format|
      if @ingredient.save
        @message = "A new ingredient was added to your shopping list."
        format.js
      else
        format.js { render :new }
      end
    end
  end

  def update
    shopping_list = ShoppingList.find(@ingredient.shopping_list_id)
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        @message = "The ingredient has been updated."
        format.js   do
          @ingredients = shopping_list.ingredients.sorted
          render :create
        end
      else
        format.js { render :edit }
      end
    end
  end

  def destroy
    @ingredients = ShoppingList.get_or_create_first.ingredients.sorted
    @ingredient.destroy
    @message = "The ingredient has been deleted."
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :quantity, :metric)
    end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @shopping_list = ShoppingList.get_or_create_first
    @ingredients = @shopping_list.ingredients.sorted
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/ingredients/_form.html.erb
<div class="row">
  <div class="col s12">
    <%= form_for(@ingredient, html: { id: "ingredient-form" }) do |f| %>
      <% if @ingredient.errors.any? %>
        <div id="error_explanation">
          <ul>
          <% @ingredient.errors.full_messages.each do |message| %>
            <li class="validation-error"><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
      </div>

      <div class="field">
        <%= f.label :metric %>
        <%= f.text_field :metric %>
      </div>
    <% end %>
  </div>
</div>

app/views/ingredients/_ingredients.html.erb
<% unless @ingredients.empty? %>
  <div class="collection">
    <% @ingredients.each do |ingredient| %>
      <div class="collection-item row ingredient-row" id="ingredient-<%= ingredient.id %>">
        <div class="col s1">
          <input type="checkbox" class="delete-ingredient" id="checkbox_<%= ingredient.id %>" data-edit-url="<%= ingredient_path(ingredient) %>"/>
          <label for="checkbox_<%= ingredient.id %>">&nbsp;</label>
        </div>
        <div class="col s10">
          <% unless ingredient.quantity.blank? %>
            <span class="new badge quantity" data-badge-caption="">
              <%= ingredient.quantity %> <%= ingredient.metric %>
            </span>
          <% end %>
          <%= ingredient.name %></a>
        </div>
        <div class="col s1 ingredient-btns">
          <!-- Ingredient Modal Trigger -->
          <a class="modal-trigger edit-ingredient-btn" data-edit-url="<%= edit_ingredient_path(ingredient) %>" id="edit-ingredient-btn_<%= ingredient.id %>" href="#ingredientModal">
            <span><i class="material-icons">mode_edit</i></span>
          </a>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
<p class="center-text">Your shopping list is empty.</p>
<% end %>

app/views/ingredients/create.js.erb
Materialize.toast('<%= @message %>', 4000)
$("body").animate({scrollTop: $("#new-ingredient-btn").position().top},1000);

$('#ingredientModal').modal('close');

$("#ingredient-list").html("<%= escape_javascript render('ingredients/ingredients') %>")

enable_form_loader_listener();

app/views/ingredients/destroy.js.erb
setTimeout(function() {
  Materialize.toast('<%= @message %>', 4000)
  $("#ingredient-list").html("<%= escape_javascript render('ingredients') %>");
  enable_form_loader_listener();
}, 500);

app/views/ingredients/edit.js.erb
Materialize.toast('<%= @message %>', 4000)

$(".ingredient-form-wrapper").html("<h4>Edit Ingredient</h4>" +
  "<%= escape_javascript render('form') %>");

app/views/ingredients/import.js.erb
$("#ingredient-list").html("<%= escape_javascript render('ingredients') %>");
Materialize.toast('<%= @message %>', 4000)
$("body").animate({scrollTop: $("#new-ingredient-btn").position().top},1000);

enable_form_loader_listener();

app/views/ingredients/import_message.js.erb
Materialize.toast('<%= @message %>', 4000)

app/views/ingredients/new.js.erb
$(".ingredient-form-wrapper").html("<h4>New Ingredient</h4>" +
  "<%= escape_javascript render('form') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="background"></div>
    <% flash.each do |message_type, message| %>
        <%= javascript_tag "Materialize.toast('#{message}', 4000)" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shopping_lists/_import_ingredients.html.erb
<div class="row">
  <div class="col s6 offset-s3">
    <%= form_tag import_ingredients_path, id:  "import-form" do %>
      <div class="row">
          <div class="row">
            <div class="input-field col s12">
              <%= text_field_tag :url, nil, placeholder: "Enter recipe URL", class: "center-text" %>
            </div>
          </div>

          <div class="row">
            <div class="col s6 offset-s3 center-text">
              <%= button_tag(class: "btn waves-effect waves-light", id: "import-ingredients-btn") do %>
                Add Ingredients
              <% end %>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shopping_lists/index.html.erb
<%= render 'import_ingredients' %>

<div class="row">
  <div class="col s6 offset-s3">
    <h1 class="center-text title"><%= @shopping_list.title %></h1>

    <div id="ingredient-list">
      <%= render 'ingredients/ingredients' %>
    </div>
  </div>
  <br>
</div>

<div class="row">
  <div class="col s6 offset-s3 center-text">
    <!-- Ingredient Modal Trigger -->
    <a class="modal-trigger waves-effect waves-light btn new-ingredient" id="new-ingredient-btn" href="#ingredientModal">New Ingredient</a>

      <!-- Ingredient Modal Structure -->
    <div id="ingredientModal" class="modal modal-fixed-footer">
      <div class="modal-content ingredient-form-wrapper">
      </div>

      <div class="modal-footer">
        <button class="modal-action modal-close waves-effect waves-green btn-flat">Cancel</button>
        <button class="waves-effect waves-green btn-flat" id="ingredient-submit-btn">Save</button>
      </div>
    </div>
  </div>
</div>